/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulb.lisa.his.client.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import ulb.lisa.his.client.client.DICOMSCU;
import ulb.lisa.his.client.client.FHIRClient;
import ulb.lisa.his.client.client.HL7Client;
import ulb.lisa.his.model.Patient;
import ulb.lisa.his.model.Person;

/**
 *
 * @author Adrien Foucart
 */
public class MainWindow extends javax.swing.JFrame {
    
    DICOMSCU scu = new DICOMSCU();
    ArrayList<Patient> patientsSearchResult = new ArrayList();
    
    FHIRClient fhirClient = new FHIRClient();
    ArrayList<org.hl7.fhir.dstu3.model.Patient> fhirPatients = new ArrayList();
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fhirPane = new javax.swing.JTabbedPane();
        patientPanel = new javax.swing.JPanel();
        personForm = new ulb.lisa.his.view.CreatePersonForm();
        sendADTButton = new javax.swing.JButton();
        adtRspLabel = new javax.swing.JLabel();
        hl7HostTextField = new javax.swing.JTextField();
        hl7PortTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        dcmPatientNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        doCFindButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivedUIDList = new javax.swing.JList<>();
        moveSelectedStudyButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fhirServerHost = new javax.swing.JTextField();
        patientFhirSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fhirSearchButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fhirSearchResultList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        fhirResultDetailTextArea = new javax.swing.JTextArea();
        fhirIDSearchTextField = new javax.swing.JTextField();
        fhirIDGetButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendADTButton.setText("Send ADT");
        sendADTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendADTButtonActionPerformed(evt);
            }
        });

        hl7HostTextField.setText("localhost");

        hl7PortTextField.setText("54321");

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personForm, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addComponent(sendADTButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hl7HostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hl7PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adtRspLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adtRspLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendADTButton)
                            .addComponent(hl7HostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hl7PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        fhirPane.addTab("Patient", patientPanel);

        jLabel1.setText("Patient Name");

        doCFindButton.setText("C-FIND");
        doCFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCFindButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(receivedUIDList);

        moveSelectedStudyButton.setText("C-MOVE");
        moveSelectedStudyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSelectedStudyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcmPatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moveSelectedStudyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doCFindButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dcmPatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(doCFindButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(moveSelectedStudyButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        fhirPane.addTab("PACS", jPanel1);

        fhirServerHost.setText("http://fhirtest.uhn.ca/baseDstu3");

        jLabel2.setText("Patient Name:");

        fhirSearchButton.setText("Search");
        fhirSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhirSearchButtonActionPerformed(evt);
            }
        });

        fhirSearchResultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fhirSearchResultListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(fhirSearchResultList);

        fhirResultDetailTextArea.setColumns(20);
        fhirResultDetailTextArea.setRows(5);
        jScrollPane4.setViewportView(fhirResultDetailTextArea);

        fhirIDGetButton.setText("Get ID");
        fhirIDGetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhirIDGetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fhirServerHost, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientFhirSearchField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fhirSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fhirIDSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fhirIDGetButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fhirServerHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFhirSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fhirSearchButton)
                    .addComponent(fhirIDSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhirIDGetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );

        fhirPane.addTab("FHIR", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fhirPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fhirPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendADTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendADTButtonActionPerformed
        Person per = personForm.getPerson();
        Patient p = new Patient();
        p.setPerson(per);
        
        String host = hl7HostTextField.getText();
        int port = Integer.valueOf(hl7PortTextField.getText());
        
        if( HL7Client.send_ADT_A01(p, host, port) ){
            adtRspLabel.setText("ACK Received");
        }
        else{
            adtRspLabel.setText("Error.");
        }
    }//GEN-LAST:event_sendADTButtonActionPerformed

    private void doCFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCFindButtonActionPerformed
        String searchPatientName = dcmPatientNameField.getText();
        ArrayList<String> receivedStudyInstanceUIDs = scu.doFindScu(searchPatientName);
        if( receivedStudyInstanceUIDs != null ){
            DefaultListModel<String> receivedListModel = new DefaultListModel();
            for( String uid : receivedStudyInstanceUIDs )
                receivedListModel.addElement(uid);
            
            receivedUIDList.setModel(receivedListModel);
        }
    }//GEN-LAST:event_doCFindButtonActionPerformed

    private void moveSelectedStudyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSelectedStudyButtonActionPerformed
        String selectedUID = receivedUIDList.getSelectedValue();
        
        scu.doMoveScu(selectedUID);
    }//GEN-LAST:event_moveSelectedStudyButtonActionPerformed

    private void fhirSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhirSearchButtonActionPerformed
        fhirPatients = fhirClient.searchPatientsByName(patientFhirSearchField.getText());
        
        PatientListModel pml = new PatientListModel(fhirPatients);
        fhirSearchResultList.setModel(pml);
        fhirSearchResultList.repaint();
    }//GEN-LAST:event_fhirSearchButtonActionPerformed

    private void fhirSearchResultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fhirSearchResultListValueChanged
        if( evt.getValueIsAdjusting() ) return;
        
        int idx = fhirSearchResultList.getSelectedIndex();
        org.hl7.fhir.dstu3.model.Patient p = fhirPatients.get(idx);
        
        setPatientInfo(p);
    }//GEN-LAST:event_fhirSearchResultListValueChanged

    private void fhirIDGetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhirIDGetButtonActionPerformed
        org.hl7.fhir.dstu3.model.Patient p = fhirClient.getPatientById(fhirIDSearchTextField.getText());
        
        setPatientInfo(p);
    }//GEN-LAST:event_fhirIDGetButtonActionPerformed
    
    private void setPatientInfo(org.hl7.fhir.dstu3.model.Patient p){
        String patientInfo = "Name: "+p.getNameFirstRep().getFamily() + " " + p.getNameFirstRep().getGivenAsSingleString() + "\n";
        if( p.getAddressFirstRep() != null ){
            patientInfo += "Address: \n";
            patientInfo += p.getAddressFirstRep().getPostalCode() + " " + p.getAddressFirstRep().getCity() + "\n";
        }
        if( p.getGender() != null ){
            patientInfo += "Gender: " + p.getGender().getDisplay() + "\n";
        }
        
        fhirResultDetailTextArea.setText(patientInfo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adtRspLabel;
    private javax.swing.JTextField dcmPatientNameField;
    private javax.swing.JButton doCFindButton;
    private javax.swing.JButton fhirIDGetButton;
    private javax.swing.JTextField fhirIDSearchTextField;
    private javax.swing.JTabbedPane fhirPane;
    private javax.swing.JTextArea fhirResultDetailTextArea;
    private javax.swing.JButton fhirSearchButton;
    private javax.swing.JList<String> fhirSearchResultList;
    private javax.swing.JTextField fhirServerHost;
    private javax.swing.JTextField hl7HostTextField;
    private javax.swing.JTextField hl7PortTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton moveSelectedStudyButton;
    private javax.swing.JTextField patientFhirSearchField;
    private javax.swing.JPanel patientPanel;
    private ulb.lisa.his.view.CreatePersonForm personForm;
    private javax.swing.JList<String> receivedUIDList;
    private javax.swing.JButton sendADTButton;
    // End of variables declaration//GEN-END:variables
}
